[package]
name = "lesson4"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
lesson2 = { path = "../lesson2" }
bril-rs.workspace = true
argh.workspace = true
itertools.workspace = true

