[package]
name = "lesson4"
version = "0.1.0"
edition = "2021"

[dependencies]
utils.workspace = true
lesson2.workspace = true
bril-rs.workspace = true
argh.workspace = true
itertools.workspace = true
log = "0.4.27"
env_logger = "0.11.8"
struct-variant = "1.0.2"

